Repository Hyperfoil/Hyperfoil, pull requests merged in 2024-07, with the labels that each got.

#374 Rate generators session pool workstealing
  api/src/main/java/io/hyperfoil/api/session/PhaseInstance.java
  benchmarks/pom.xml
  benchmarks/src/main/java/io/hyperfoil/core/counters/CountersScalability.java
  benchmarks/src/main/java/io/hyperfoil/core/harness/EventLoopGroupHarnessExecutor.java
  benchmarks/src/main/java/io/hyperfoil/core/impl/FakeEventExecutor.java
  benchmarks/src/main/java/io/hyperfoil/core/impl/FakeSession.java
  benchmarks/src/main/java/io/hyperfoil/core/impl/PoolBenchmark.java
  benchmarks/src/main/java/io/hyperfoil/core/impl/PoolReserveBenchmark.java
  core/pom.xml
  core/src/main/java/io/hyperfoil/core/impl/AffinityAwareSessionPool.java
  core/src/main/java/io/hyperfoil/core/impl/LockBasedElasticPool.java
  core/src/main/java/io/hyperfoil/core/impl/OpenModelPhase.java
  core/src/main/java/io/hyperfoil/core/impl/PhaseInstanceImpl.java
  core/src/main/java/io/hyperfoil/core/impl/SimulationRunner.java
  core/src/test/java/io/hyperfoil/core/impl/ElasticPoolTest.java
  core/src/test/java/io/hyperfoil/core/impl/EventExecutorSessionPoolTest.java
  core/src/test/java/io/hyperfoil/core/impl/LockBasedElasticPoolTest.java
  core/src/test/java/io/hyperfoil/core/impl/PoolTest.java
  core/src/test/java/io/hyperfoil/core/test/CustomExecutorRunner.java
  pom.xml
Labels: enhancement

#382 Reduce maxRequests to 1 for Wrk HTTP 1.1
  cli/src/main/java/io/hyperfoil/cli/commands/WrkAbstract.java
Labels: enhancement

#388 Extends max sequences and requests wrk settings to HTTP 2 as well
  cli/src/main/java/io/hyperfoil/cli/commands/WrkAbstract.java
Labels: enhancement

#396 docs: fix publish date for past blogs
  docs/site/content/en/blog/news/2021-02-09-hf-beginner-guide-2.md
  docs/site/content/en/blog/news/2021-02-16-hf-beginner-guide-3/index.md
Labels: documentation, backport

#401 Create CNAME for website deployment
  docs/site/static/CNAME
Labels: backport

#409 Fix incorrect log messages
  clustering/src/main/java/io/hyperfoil/Hyperfoil.java
  clustering/src/main/java/io/hyperfoil/clustering/ControllerServer.java
  clustering/src/main/java/io/hyperfoil/clustering/ControllerVerticle.java
  clustering/src/main/java/io/hyperfoil/clustering/Zipper.java
  clustering/src/main/java/io/hyperfoil/controller/Data.java
  clustering/src/main/java/io/hyperfoil/deploy/ssh/SshDeployedAgent.java
  clustering/src/main/java/io/hyperfoil/deploy/ssh/SshDeployer.java
  core/src/main/java/io/hyperfoil/core/hooks/ExecRunHook.java
  core/src/main/java/io/hyperfoil/core/util/CpuWatchdog.java
  http/src/main/java/io/hyperfoil/http/connection/CustomHttp2ConnectionHandler.java
  http/src/main/java/io/hyperfoil/http/connection/Http1xConnection.java
  k8s-deployer/src/main/java/io/hyperfoil/deploy/k8s/K8sDeployer.java
  plugins/maven/src/main/java/io/hyperfoil/maven/RunMojo.java
Labels: enhancement, good first issue
